contentDir = "content"
layoutDir = "layouts"
publishDir = "public"
buildDrafts = false
baseURL = "http://yoursite.example.com/"
canonifyURLs = true
themesDir = "themes"
theme = "hugo-listing"

[taxonomies]
  category = "categories"
  tag = "tags"

  description = "Lista NOC"
  author = "sr erisso"

[params]
    